# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#

name: Sync from tflite-micro
run-name: ${{ github.actor }} is launching automatic sync from tflm repo

on:
  schedule:
    # 10am UTC is 3am or 4am PT depending on daylight savings.
    - cron: '0 0 1 1/2 *'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'schedule' && github.repository == 'Gostas/tflite-micro-arduino-examples')

    steps:
      - uses: actions/setup-python@v5
        with:
            python-version: 3.9
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Sync the code
        run: |
          pip3 install six Pillow Wave numpy
          git config --local user.name "Gostas"
          git config --local user.email "konst.pap@hotmail.com"

          ./scripts/sync_from_tflite_micro.sh

          git checkout -b "AutoSync"
          git add *

          if [[ $(git status --porcelain | wc -l) == 0 ]]; then
            echo "no changes"
          else
            git commit -m "Sync from tflite-micro."
          fi

          git push --set-upstream origin AutoSync

      - name: Create Pull Request
        run: |
          gh repo set-default Gostas/tflite-micro-arduino-examples
          gh pr create -B main -H AutoSync -t 'Automated sync with TFLM' -b 'Created by Github action' -r Gostas
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}